### ISSUE TITLE
Neo4j download overwrites existing graph.db

### ISSUE THREAD

**Issue by gayanadarajan** [hetio/hetionet#1]
Hi, 

I downloaded Hetionet onto my local machine and could browse it. However, I can't seem to locate my existing GraphDB which I created beforehand. How do I retrieve it?

Thanks

**Comment by dhimmel** [comment]
@gayanadarajan I'm assuming that you're talking about Hetionet in Neo4j. Can you provide more details such as:
- what operating system and version of Neo4j you're using
- how did you install Neo4j
- more details on how you installed the Hetionet database into Neo4j

**Comment by gayanadarajan** [comment]
Yes, on Neo4j. I'm on MacOS Sierra and Neo4j 3.0.3 (downloaded the enterprise version and just unzipped a tar file I believe).

Downloaded Hetionet by following setup instructions here (curl):
https://github.com/dhimmel/hetionet/tree/neo4j-3.0/hetnet/neo4j

After that I no longer see any other instances of graph.db in my neo4j directory than the one dated yesterday (presumably Hetionet). Maybe I should have backed it up before the download.

**Comment by dhimmel** [comment]
@gayanadarajan I'm afraid your original database may be gone 😿 . Sorry about that!

The recommended workaround is to rename your existing database (i.e. `mv graph.db original-graph.db`) before running:

``` sh
curl --location https://github.com/dhimmel/hetionet/raw/neo4j-3.0/hetnet/neo4j/hetionet-v1.0.db.tar.bz2 | tar --extract --bzip2
```

You've convinced me that in the future, we should use a custom directory name for the hetionet database, so this won't happen. We'll have to change the `dbms.active_database` property of `neo4j.conf`, but that's not a big deal.

**Comment by gayanadarajan** [comment]
Yep, I wasn't aware about the overwrite as it was my first time downloading a new DB on top of an existing one. I suppose if something like:

1) Ensure Java and Neo4j are installed
2) Stop neo4j server if running
3) Back up existing DB (i.e. rename graph.db to another name)

Before the current instructions, it would be a bit more useful for folk like me.

Would be good to have uninstall hetionet instructions, e.g. delete graph.db?

Cheers.
