### ISSUE TITLE
neo4j.het.io database down on 2018-12-19

### ISSUE THREAD

**Issue by im281** [hetio/hetionet#14]
Is the hetionet database down?

**Comment by dhimmel** [comment]
Thanks @im281 for the report. Yes it was down, such that the Neo4j Browser was being served but the underlying database was not functional. I restarted the server so it's working now.

Not sure exactly what caused it to crash or how we can automatically detect this in the future. Ideas:

1. upgrade to the latest neo4j minor release (in case a relevant bug fix has been deployed)
2. run a script every hour that does a basic query. If that fails, reboot the server.

**Comment by im281** [comment]
Hi Daniel,
I am a Scientist working on Mass Spectrometry instrumentation and data
processing software. I was wondering if you would be interested in
discussing an idea I had regarding connecting knowledge graphs to mass
spectrometry experiments and automatic method development
Best regards,
Iman
