### ISSUE TITLE
Can't run-docker.sh [Ubuntu 16.04, Docker 1.12.5]

### ISSUE THREAD

**Issue by zeluspudding** [hetio/hetionet#3]
Hello Daniel,
Thanks for your speedy reply on [How do I run the Hetionet v1.0 docker container?](http://stackoverflow.com/a/41410352/3491991). Per your suggestion I'm moving the conversation here and will update back to Stackoverflow (all credit to you).

 > Hetionet docker has a [special run command](https://github.com/dhimmel/hetionet/blob/319673109a5f7948dd5618843bf0015e8dc776ff/hetnet/neo4j/docker/host/run-docker.sh), `sh ~/run-docker.sh`, which is executed [after running](https://github.com/dhimmel/hetionet/tree/neo4j-3.0/hetnet/neo4j/docker#deploying-the-docker) `docker pull dhimmel/hetionet`. 

### Docker image doesn't seem to be moving run-docker.sh to the right directory
On digitalocean I pull the image and enter `sh ~/run-docker.sh` then get this output:
![cant_open_root](https://cloud.githubusercontent.com/assets/8431341/21578987/e0d4c886-cf5c-11e6-9ff8-7c46277b1476.PNG)
The root directory looks like this:
![root_directory](https://cloud.githubusercontent.com/assets/8431341/21579048/0d7678b4-cf60-11e6-9254-37d5001f9b5b.PNG)

If I run the image locally on kitematic I get this:
![error_log](https://cloud.githubusercontent.com/assets/8431341/21579006/98b0e70a-cf5d-11e6-8505-02b0cf2bb7ce.PNG)

### I may have run hetionet so many times that my droplet is full:
Running `docker run --interactive --tty dhimmel/hetionet bash` to explore the image, per your suggestion, gives this output:
![no_space](https://cloud.githubusercontent.com/assets/8431341/21579028/6ea332e6-cf5e-11e6-8ffc-0da84e6ec86f.PNG)

It turns out I have run hetionet eight times. `docker ps -a` outputs this:
![other_container_exit_codes](https://cloud.githubusercontent.com/assets/8431341/21579025/3aa8681c-cf5e-11e6-9c2d-e96c165f9808.png)

So I remove all the containers by running `docker rm $(docker ps -a -q)`. However re-running `docker run --interactive --tty dhimmel/hetionet bash` (or other memory consuming commands) result in the same "No space left on device" message. How do I reclaim this space if `docker rm $(docker ps -a -q)` didn't do the job?

**Comment by dhimmel** [comment]
> Docker image doesn't seem to be moving `run-docker.sh` to the right directory

The files in the [`host` directory](https://github.com/dhimmel/hetionet/tree/319673109a5f7948dd5618843bf0015e8dc776ff/hetnet/neo4j/docker/host) of this repo are not part of the Docker image. Instead, they must be moved (manually for now) to the home directory of your DigitalOcean droplet. As a start, you may only need [`run-docker.sh`](https://github.com/dhimmel/hetionet/blob/319673109a5f7948dd5618843bf0015e8dc776ff/hetnet/neo4j/docker/host/run-docker.sh), which is the command to run the Docker in production. If you want to proceed without an SSL certificate, then remove the line: 

```
  --volume=$HOME/ssl:/var/lib/neo4j/certificates \
```

**Comment by dhimmel** [comment]
Regarding the `No space left on device` error, perhaps this could occur if you're not using a volume for storing the Neo4j database (which is enabled with `--volume=$HOME/hetionet-data:/data`).

What is your immediate goal? Do you just want to have a personal Hetionet instance to query or are you trying something else?

**Comment by zeluspudding** [comment]
I'm preparing a custom demo much like you have with hetionet but with finance data. What you've done is a great scaffold for my need so the plan is to reverse engineer your processes and modify to suit.

I found workarounds to all the problems I had:

**Problem:** `No space left on device`
**Solution:** Skip figuring it out and just [rebuild the droplet](https://www.digitalocean.com/community/questions/ubuntu-restore-to-original-droplet)

**Problem:** Running file [`run-docker.sh`](https://github.com/dhimmel/hetionet/blob/319673109a5f7948dd5618843bf0015e8dc776ff/hetnet/neo4j/docker/host/run-docker.sh) from my droplet's root ($HOME) directory made docker fail/complain about `\r` on the first line (`docker run \`). I'm guessing it had something to do with [carriage returns](https://github.com/tiangolo/babun-docker/issues/18#issuecomment-218035854)
**Solution:** Instead of trying to fix that I skipped uploading your host files and just ran this in my droplet's shell:

     docker run \
        --detach \
        --publish=7474:7474 \
       --publish=7473:7473 \
       --publish=7687:7687 \
       --volume=$HOME/hetionet-data:/data \
       --volume=$HOME/neo4j-logs:/var/lib/neo4j/logs \
       --env=NEO4J_dbms_memory_pagecache_size=1G \
       --env=NEO4J_dbms_memory_heap_maxSize=512 \
         dhimmel/hetionet

This is different from your `run-docker.sh` command in that it doesn't care about SSL and maps container ports 7474 to host port 7474. Same for 7473 to 7473 (whereas yours did 80:7474 and 443:7473).

**Side Problem:** Uploading stuff to droplet
**Solution:** Skip messing with cert files and [just connect](https://www.digitalocean.com/community/questions/how-i-get-ftp-login-with-filezilla) to the droplet in filezilla doing the following

     Host: sftp://Your_IP
     User: root (or your username)
     Password: Your password

**Comment by dhimmel** [comment]
> I'm preparing a custom demo much like you have with hetionet but with finance data. What you've done is a great scaffold for my need so the plan is to reverse engineer your processes and modify to suit.

Awesome -- can't wait to see your database! I'd recommend making your own Docker image. You can use the [`Dockerfile`](https://github.com/dhimmel/hetionet/blob/319673109a5f7948dd5618843bf0015e8dc776ff/hetnet/neo4j/docker/Dockerfile) as a template -- you'll want to remove the Piwik analytics (or swap in your own analytics).
