### ISSUE TITLE
Local files

### ISSUE THREAD

**Issue by victorconan** [hetio/hetionet#39]
Hi! I am interested in the completed hetnet and I saw this from the `import.ipynb`:

```
Several files were not uploaded to dhimmel/integrate due to filesize. These files are copied over locally.
```
Is it possible to download those local files?

Thanks!

**Comment by dhimmel** [comment]
Yes this is in [`import.ipynb`](https://github.com/hetio/hetionet/blob/31a97c93db46cc0224516ecbe2a7baa0067bd259/import.ipynb), which was a script to populate this reposity. This notebook copies files from `dhimmel/integrate`, some on the GitHub and some created locally, to populate `hetio/hetionet`.

Those local files end up getting tracked in `hetio/hetionet`. Specifically it looks like the files that were imported from local paths were:

1. the permuted JSON networks at [`hetnet/permuted/json/`](https://github.com/hetio/hetionet/tree/31a97c93db46cc0224516ecbe2a7baa0067bd259/hetnet/permuted/json)
2. the permuted neo4j networks at [`hetnet/permuted/neo4j/`](https://github.com/hetio/hetionet/tree/neo4j-2.3/hetnet/permuted/neo4j) on the `neo4j-2.3` branch.

> I am interested in the completed hetnet

This repo contains the completed hetnet in many different formats. `import.ipynb` doesn't sound relevant to your use case, unless you are trying to create a different network with a distinct data distribution repo like this.

**Comment by victorconan** [comment]
I see. Thanks, Daniel!
