### ISSUE TITLE
http://neo4j.het.io/browser/ time out

### ISSUE THREAD

**Issue by yingding** [hetio/hetionet#44]
At the time of writing (UTC timestamp: 1637594788), i was not able to connect to http://neo4j.het.io/browser/ and got a time out error.
```
UTC timestamp: 1637594788
GMT: Monday, 22 November 2021 15:26:28
```
To convert the timestamp to your timezone time with https://www.epochconverter.com/

Thanks for your help in advance.

**Comment by dhimmel** [comment]
Thanks for the report. I restarted the instance so it's back up now.

@dongbohu any suggestions on an automated way to restart the VM or docker instance when the Neo4j database stops working? We could do a daily restart such that an outage would never be >24 hours? Or could we detect whether the database fails to respond to a query... and if so restart?

**Comment by yingding** [comment]
If you can replace the docker with microk8s on an Ubuntu 20.04 LTS, the microk8s will restart the pod/container by itself. There will be no outage.

**Comment by dongbohu** [comment]
@dhimmel I never used `microk8s` before. The simplest solution I can think of is to launch a http(s) request and see whether the response is valid. If not, restart the docker container.

**Comment by dhimmel** [comment]
Closing since we now have uptime alerts, see https://github.com/hetio/hetionet/issues/45.
