### ISSUE TITLE
Question on metrics

### ISSUE THREAD

**Issue by ayujain04** [hetio/hetionet#55]
I was able to get some paths and they are accompanied by two metrics PDP and percent_of_DWPC. Could you help me understand what those are?

**Comment by dhimmel** [comment]
See "Feature computation metrics" in https://doi.org/10.1371/journal.pcbi.1004259.

Also this sentence from https://greenelab.github.io/connectivity-search-manuscript/:

> Since the DWPC is a summation of a path metric (called the path degree product), it is straightforward to calculate the proportion of a DWPC attributable to an individual path.
