### ISSUE TITLE
What does it mean if something up regulates a disease in this context? 

### ISSUE THREAD

**Issue by ayujain04** [hetio/hetionet#56]
Hey! 

Was toying around with a few metapaths are realized that some result in a drug "upregulating" a disease. 

Does this indicate that the drug could make the symptoms of a disease worse in this specific pathway?

**Comment by ayujain04** [comment]
Also, I have a question about paths like this:

Is this saying that the Cyclosporine and the Rivastigmine and Donepzeli cancel out? 

Essentially, how should I go about interpreting when there is more than one compound in a path starting at compound and ending at a disease?

![Screenshot 2023-07-19 at 10 07 59 AM](https://github.com/hetio/hetionet/assets/88155816/52d24379-9de5-4d16-ade6-bc462c0280b1)

**Comment by dhimmel** [comment]
> drug "upregulating" a disease

There is no direct Drug-upregulates-Disease metaedge in Hetionet. But yes drugs can upregulate genes as well as diseases can upregulate genes.

> how should I go about interpreting when there is more than one compound in a path starting at compound and ending at a disease?

The path will never contain the same compound twice, but if the metapath contains two Compound metanodes than the path will contain two compounds. You should interpret these paths similarly to any other. First consider the metapath. Do you care about the meaning/connectivity that the metapath conveys? Is so, then you might care about an individual path following that metapath. But also note there could be 1000s or more paths for a given metapath and source+target node, hence any individual path might have very little meaning on its own. Although all the paths together can generate a meaningful signal through a metric like DWPC.

> Is this saying that the Cyclosporine and the Rivastigmine and Donepzeli cancel out?

All three paths you show follow metapaths that traverse noisy metaeges (covaries, down/up-regulates). I wouldn't read too much into any individual path in that case.

Try to get a conceptual understanding of each metaedge by reading the Project Rephetio manuscript and discussions. From there you can work up a better understanding of metapaths and want biological signal they might represent.

**Comment by ayujain04** [comment]
Okay, thank you!
